# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a6e3d5db5c7e7622766c5310c9b298e24e05ddd8139104351f06f010568e26ceb3635dd45dcd55c8e98cdbb23150ee3a52b97b96c12f6540e706fcdc58a143

test:
  secret_key_base: e8ca7d3f84073229bc10c4d64025beb82cc3ce5f53a5419be8494176f840b78626892212e07844b0647241dbbe6a8c160f36633b0a921402b915f0db90cca1a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
